Repository espressif/esp-idf, pull requests merged in 2021-12, with the labels that each got.

#7958 fix: missing initializer waring in esp_eth (IDFGH-6293)
  components/esp_eth/include/esp_eth.h
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#7796 docs: Spelling error fix
  docs/en/api-reference/peripherals/pcnt.rst
  docs/en/api-reference/protocols/esp_tls.rst
  docs/en/api-reference/protocols/esp_websocket_client.rst
Labels: PR-Sync-Merge, PR-Sync-Update

#7971 bugfix: Conflicting declaration error when include<rom/secure_boot.h> (IDFGH-6308)
  components/esp_rom/include/esp32/rom/secure_boot.h
  components/esp_rom/include/esp32c3/rom/secure_boot.h
  components/esp_rom/include/esp32h2/rom/secure_boot.h
  components/esp_rom/include/esp32s2/rom/secure_boot.h
  components/esp_rom/include/esp32s3/rom/secure_boot.h
  components/esp_rom/include/esp8684/rom/secure_boot.h
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#7978 Minor: typo (IDFGH-6316)
  docs/en/api-guides/unit-tests.rst
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#7878 Improve code structure of ksz80xx PHY driver and add more PHYs from this series (IDFGH-6203)
  components/esp_eth/include/esp_eth_phy.h
  components/esp_eth/src/esp_eth_phy_ksz80xx.c
  examples/common_components/protocol_examples_common/Kconfig.projbuild
  examples/common_components/protocol_examples_common/connect.c
  examples/ethernet/basic/main/Kconfig.projbuild
  examples/ethernet/basic/main/ethernet_example_main.c
  examples/ethernet/eth2ap/main/Kconfig.projbuild
  examples/ethernet/eth2ap/main/ethernet_example_main.c
  examples/ethernet/iperf/main/Kconfig.projbuild
  examples/ethernet/iperf/main/cmd_ethernet.c
  examples/network/simple_sniffer/main/Kconfig.projbuild
  examples/network/simple_sniffer/main/simple_sniffer_example_main.c
Labels: Resolution: Done, Status: Resolved

#8037 Don't return a hard coded errno in vfs_fat_access (IDFGH-6377)
  components/fatfs/vfs/vfs_fat.c
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8041 print Firmware Upgrade URL to help user debug (IDFGH-6382)
  examples/system/ota/simple_ota_example/main/simple_ota_example.c
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#7966 Changed argument pointer to correct data (IDFGH-6303)
  examples/network/simple_sniffer/main/cmd_sniffer.c
Labels: Status: Reviewing, PR-Sync-Merge

#8001 Added results count to MDNS (IDFGH-6340)
  components/mdns/include/mdns.h
  components/mdns/mdns.c
Labels: Status: Reviewing

#8107 Fix GDB backtraces in optimized builds (IDFGH-6444)
  components/freertos/Kconfig
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8139 ledc.h - fix extern "C" to include ledc_cb_register() (IDFGH-6484)
  components/driver/include/driver/ledc.h
Labels: Status: Done, Resolution: Done, PR-Sync-Merge
