Repository espressif/esp-idf, pull requests merged in 2021-09, with the labels that each got.

#7474 Missing dependency for idf.py 'encrypted-flash' target (IDFGH-5766)
  components/app_update/CMakeLists.txt
Labels: Status: Done, Resolution: Done

#7536 tcp_transport: Fix NULL pointer dereference in esp_transport_esp_tls_… (IDFGH-5834)
  components/tcp_transport/transport_ssl.c
Labels: Resolution: Done, Status: Resolved

#7582 miscellaneous code updates to conform with code styling (IDFGH-5884)
  components/bt/host/bluedroid/api/include/api/esp_gap_ble_api.h
Labels: Status: In Progress
