Repository espressif/esp-idf, pull requests merged in 2022-01, with the labels that each got.

#8013 Add message about alternative functions. (IDFGH-6352)
  components/vfs/include/esp_vfs_dev.h
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8169 fix fatfs_create_spiflash_image() feature (IDFGH-6383) (IDFGH-6518)
  components/fatfs/fatfsgen.py
  components/fatfs/fatfsgen_utils/fs_object.py
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8100 monitor: Print buffer when reading an escape character (IDFGH-6443)
  tools/idf_monitor_base/ansi_color_converter.py
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8172 Fix compile issue when TinyUSB task is not enabled. (IDFGH-6521)
  components/tinyusb/additions/src/tusb_tasks.c
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8201 Fix typo (IDFGH-6556) (IDFGH-6557)
  docs/en/api-guides/app_trace.rst
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8103 Fix mDNS memory leak (IDFGH-6448)
  components/mdns/mdns.c
Labels: Status: Reviewing

#8164 Replace lwIP byte order functions with built-in functions (IDFGH-6512)
  components/lwip/port/esp32/include/arch/cc.h
Labels: Resolution: Done, Status: Resolved, PR-Sync-Merge
