Repository espressif/esp-idf, pull requests merged in 2022-05, with the labels that each got.

#8788 Add idf.py monitor argument --no-reset (-R) (IDFGH-7189)
  tools/idf_monitor.py
  tools/idf_monitor_base/argument_parser.py
  tools/idf_monitor_base/serial_handler.py
  tools/idf_monitor_base/serial_reader.py
  tools/idf_py_actions/serial_ext.py
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8825 fix small typos in the comments (documentation) (IDFGH-7231)
  components/driver/include/driver/rmt.h
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8834 bump mypy version (IDFGH-7240)
  .pre-commit-config.yaml
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8851 Fixed the commented out coap_new_optlist() in the coap_client example. (IDFGH-7262)
  examples/protocols/coap_client/main/coap_client_example_main.c
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8853 修复Touch Element文档标题错误 (IDFGH-7264)
  docs/en/api-reference/peripherals/touch_element.rst
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8888 utils.py: fix assert range with hour (IDFGH-7300)
  components/fatfs/fatfsgen_utils/utils.py
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8955 Tools: fix idf.py monitor reset with hotkey with --no-reset arg (IDFGH-7375)
  tools/idf_monitor_base/serial_reader.py
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8962 Update echo_example_main.c (IDFGH-7382)
  examples/protocols/icmp_echo/main/echo_example_main.c
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8981 Tools: Add missing DTR/RTS set before serial port open on reconnect (IDFGH-7403)
  tools/idf_monitor_base/serial_reader.py
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8997 Clean up botched merge (IDFGH-7419)
  examples/bluetooth/blufi/README.md
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8990 esp_netif_leave_ip6_multicast_group_api: Fixup inversion error causing error prints (IDFGH-7412)
  components/esp_netif/lwip/esp_netif_lwip.c
Labels: Status: Done, Resolution: Done

#9001 usbh_print_intf_desc prints wrong value for tbInterfaceClass (IDFGH-9000)
  components/usb/usb_helpers.c
Labels: PR-Sync-Merge

#8972 Fix Typo in bluedroid spp client readme (IDFGH-7392)
  examples/bluetooth/bluedroid/ble/ble_spp_client/README.md
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#9033 add address field to read_rmt_name_param in legacy bluetooth (IDFGH-7459)
  components/bt/host/bluedroid/api/include/api/esp_gap_bt_api.h
  components/bt/host/bluedroid/btc/profile/std/gap/btc_gap_bt.c
  components/bt/host/bluedroid/stack/btm/btm_inq.c
Labels: Status: Done, Resolution: Done

#8076 example: Synchronize includes in BLE walkthrough (IDFGH-6417)
  examples/bluetooth/bluedroid/ble/gatt_server/tutorial/Gatt_Server_Example_Walkthrough.md
Labels: Status: Done, Resolution: Done, PR-Sync-Merge
