Repository espressif/esp-idf, pull requests merged in 2022-07, with the labels that each got.

#9213 Fix out of range in mcpwm example (IDFGH-7666)
  examples/peripherals/mcpwm/mcpwm_bldc_hall_control/main/mcpwm_bldc_hall_control_example_main.c
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#9255 Fix datatype conversion compiler error #9254 (IDFGH-7713)
  components/esp_system/include/esp_debug_helpers.h
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#9264 Fix tinyusb_driver_install (dangling pointer) (IDFGH-7723)
  components/tinyusb/additions/src/tinyusb.c
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#9138 Reverts Backtrace: format to what it used to be (IDFGH-7580)
  components/esp_system/port/arch/xtensa/debug_helpers.c
Labels: Status: Done, Resolution: Done

#9311 Expand lcd/i80_controller example to support ILI9341 display (IDFGH-7775)
  examples/peripherals/lcd/i80_controller/README.md
  examples/peripherals/lcd/i80_controller/main/Kconfig.projbuild
  examples/peripherals/lcd/i80_controller/main/i80_controller_example_main.c
Labels: Status: Done, Resolution: Done, Status: Reviewing, PR-Sync-Merge

#9365 fix write to null pointer if malloc failed (IDFGH-7836)
  examples/wifi/espnow/main/espnow_example_main.c
  examples/wifi/ftm/main/ftm_main.c
Labels: Status: Done, Resolution: Done

#9385 Tools: fix a crash in idf_monitor.py (IDFGH-7859)
  tools/idf_monitor.py
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#9408 nvs_partition_gen: Allow up to 4000 byte strings with NVS V2 (IDFGH-7884)
  components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#9446 Add missing comma (IDFGH-7928)
  components/heap/port/esp32s3/memory_layout.c
Labels: Status: Done, Resolution: Done, PR-Sync-Merge
