Repository espressif/esp-idf, pull requests merged in 2022-12, with the labels that each got.

#10292 fix small bug when logging eth error (IDFGH-8869)
  components/esp_eth/src/esp_eth_mac_w5500.c
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#10304 Fixed mismatch in printf types (IDFGH-8883)
  examples/get-started/hello_world/main/CMakeLists.txt
  examples/get-started/hello_world/main/hello_world_main.c
Labels: Status: In Progress, PR-Sync-Merge

#10328 Improve certificate logging (IDFGH-8911)
  components/esp-tls/esp_tls_mbedtls.c
  components/mbedtls/port/esp_ds/esp_rsa_sign_alt.c
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#10329 Fix type of cast (IDFGH-8910)
  components/esp_http_server/src/httpd_main.c
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#10334 Set `errno` in `adjtime` (IDFGH-8915)
  components/newlib/time.c
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#10356 Enforce that SPI Flash pins are not for regular usage. (IDFGH-8942)
  docs/en/hw-reference/esp32/get-started-wrover-kit.rst
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#10382 Update DFU docs for flash encryption (IDFGH-8970)
  docs/en/api-guides/dfu.rst
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#10391 [Docs] specify Digital Signature byte order, and esp_ds_sign() clarification (IDFGH-8978)
  components/esp_hw_support/include/esp_ds.h
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#10141 [Heap Trace Standalone] improvements to formatting, code, comments (IDFGH-8699)
  components/app_trace/heap_trace_tohost.c
  components/heap/heap_trace_standalone.c
  components/heap/include/esp_heap_trace.h
  docs/en/api-reference/system/heap_debug.rst
  tools/ci/check_copyright_ignore.txt
Labels: Status: Done, Resolution: Done
