Repository espressif/esp-idf, pull requests merged in 2022-04, with the labels that each got.

#8686 Just a markdown syntax typo in the docs... (IDFGH-7069)
  docs/en/api-reference/peripherals/spi_master.rst
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#8692 Add lwip dns debug option. (IDFGH-7076)
  components/lwip/Kconfig
  components/lwip/port/esp32/include/lwipopts.h
Labels: Resolution: Done, Status: Resolved

#8395 transport_ws: Parse and expose frame fin flag (IDFGH-6767)
  components/tcp_transport/include/esp_transport_ws.h
  components/tcp_transport/transport_ws.c
Labels: Status: Reviewing

#8767 Fixing a file name typo (plug.c) (IDFGH-7165)
  docs/en/api-guides/build-system.rst
Labels: Status: Done, Resolution: Done, PR-Sync-Merge
