Repository espressif/esp-idf, pull requests merged in 2023-03, with the labels that each got.

#10922 doc: fix a small typo for check_kconfigs.py (IDFGH-9573)
  docs/en/api-reference/kconfig.rst
Labels: Status: Done, Resolution: Done

#10970 Bugfix: Fix compile error for ESP32 FSM ULP ADC Example (IDFGH-9623)
  examples/system/ulp_fsm/ulp_adc/main/ulp_adc_example_main.c
Labels: Status: Reviewing, PR-Sync-Merge

#10935 export: avoid error on unbound variable (IDFGH-9586)
  export.sh
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#10947 Update partitions_example.csv (IDFGH-9599)
  examples/peripherals/i2c/i2c_tools/partitions_example.csv
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#10967 [esp-tls] Add addr_family option to esp_tls_cfg_t (IDFGH-9620)
  components/esp-tls/esp_tls.c
  components/esp-tls/esp_tls.h
Labels: Status: Done, Resolution: Done, PR-Sync-Merge
