Repository espressif/esp-idf, pull requests merged in 2023-05, with the labels that each got.

#10895 Fix possible conversion errors by using __builtin_ffsll (IDFGH-9541)
  components/xtensa/include/xt_utils.h
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#11204 Fix function signature in flash suspend example (IDFGH-9888)
  examples/system/flash_suspend/main/app_main.c
Labels: Status: Opened, PR-Sync-Merge

#11215 improve thread safety in esp_timer (IDFGH-9920)
  components/esp_timer/src/esp_timer.c
Labels: Status: Opened, Status: Done, Resolution: NA, PR-Sync-Merge

#11326 correct typo in reference to ESP-IDF repo (IDFGH-10049)
  docs/en/migration-guides/release-5.x/5.0/protocols.rst
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#11245 Modifies the argument of the sizeof statement to a legitimate array name (IDFGH-9952)
  components/app_trace/sys_view/ext/logging.c
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#11394 Fix typo in Linux/macOS getting started docs (IDFGH-10119)
  docs/en/get-started/linux-macos-start-project.rst
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#11402 esp_ds: ignore releasing mutex if not called from same task (IDFGH-10131)
  components/mbedtls/port/esp_ds/esp_rsa_sign_alt.c
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#11388 Update esp_cpu.h to include esp_attr.h (IDFGH-10113)
  components/esp_hw_support/include/esp_cpu.h
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#11405 Fix initialization macros for twai_timing_config_t not setting .clk_src and .brp (IDFGH-10134)
  components/hal/include/hal/twai_types.h
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#11390 fix(c++): invalid conversion from int to enumeration (IDFGH-10115)
  components/esp_netif/include/esp_netif_sntp.h
Labels: Status: Done, Resolution: NA
