Repository espressif/esp-idf, pull requests merged in 2023-10, with the labels that each got.

#12247 Keep export.sh Bourne Shell compatible (IDFGH-11073)
  export.sh
Labels: Status: Done, Resolution: Done

#12384 docs: fix i2s section formatting (IDFGH-11218)
  components/driver/i2s/include/driver/i2s_common.h
  components/driver/i2s/include/driver/i2s_pdm.h
  components/driver/i2s/include/driver/i2s_std.h
  components/driver/i2s/include/driver/i2s_tdm.h
  components/driver/i2s/include/driver/i2s_types.h
  docs/en/api-reference/peripherals/i2s.rst
  tools/ci/check_public_headers_exceptions.txt
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#12424 fix(driver/gpio): Fix SIG_GPIO_OUT_IDX comment for signal connect
  components/esp_rom/include/esp_rom_gpio.h
Labels: PR-Sync-Merge
