Repository espressif/esp-idf, pull requests merged in 2023-07, with the labels that each got.

#11692 docs : fix a typo in docs/zh_CN/api-reference/storage/sdmmc.rst (IDFGH-10441)
  docs/zh_CN/api-reference/storage/sdmmc.rst
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#11281 fix usb resume bug on esp32sx (IDFGH-10000)
  components/tinyusb/additions/src/portable/espressif/esp32sx/dcd_esp32sx.c
Labels: Status: Done, Resolution: Done

#11509 [Heap Trace Standalone] do not allocate memory until init is called (IDFGH-10247)
  components/heap/Kconfig
  components/heap/heap_trace_standalone.c
  components/heap/test_apps/heap_tests/sdkconfig.ci.heap_trace_hashmap
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#11836 fix: create-project & create_component with proper file permission (IDFGH-10599)
  tools/idf_py_actions/create_ext.py
  tools/test_build_system/test_common.py
Labels: Status: Done, Resolution: Done, PR-Sync-Merge

#11878 feat(mcpwm): Allow for pull up/down to be configurable on generators (IDFGH-10647)
  components/driver/mcpwm/include/driver/mcpwm_gen.h
  components/driver/mcpwm/mcpwm_gen.c
Labels: Status: Done, Resolution: NA, PR-Sync-Merge
