Repository espressif/esp-idf, pull requests merged in 2023-11, with the labels that each got.

#12514 Update ledc_basic_example_main.c the order of initializers should match the declaration (IDFGH-11370)
  examples/peripherals/ledc/ledc_basic/main/ledc_basic_example_main.c
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#12523 fix: assert failed in example uart_async_rxtxtasks (IDFGH-11380)
  examples/peripherals/uart/uart_async_rxtxtasks/main/uart_async_rxtxtasks_main.c
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#11457 Remove semicolons from ESP_IP4ADDR_INIT and ESP_IP6ADDR_INIT macros (IDFGH-10189)
  components/esp_netif/include/esp_netif_ip_addr.h
Labels: Status: Done, Resolution: NA

#11942 BT Classic: support for 32 and 128-bit custom UUIDs (IDFGH-10721)
  components/bt/host/bluedroid/bta/dm/bta_dm_act.c
  components/bt/host/bluedroid/bta/dm/include/bta_dm_int.h
  components/bt/host/bluedroid/bta/include/bta/bta_sys.h
  components/bt/host/bluedroid/bta/sys/bta_sys_conn.c
  components/bt/host/bluedroid/btc/profile/std/sdp/btc_sdp.c
  components/bt/host/bluedroid/stack/btm/btm_inq.c
  components/bt/host/bluedroid/stack/include/stack/btm_api.h
Labels: Status: Done, Resolution: NA

#12551 Minor fix style-guide.rst (IDFGH-11413)
  docs/en/contribute/style-guide.rst
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#11828 fix receicing of DHCP vendor info (IDFGH-10591)
  components/lwip/port/hooks/lwip_default_hooks.c
Labels: Status: Done, Resolution: NA

#12525 change(console): print sorted help (IDFGH-11382)
  components/console/commands.c
  components/console/test_apps/console/main/test_console.c
Labels: Status: Done, Resolution: NA, PR-Sync-Update

#12567 Add option to configure FATFS_USE_LABEL boolean (IDFGH-11429)
  components/fatfs/Kconfig
  components/fatfs/src/ffconf.h
Labels: Status: Done, Resolution: NA, PR-Sync-Merge
