Repository espressif/esp-idf, pull requests merged in 2024-04, with the labels that each got.

#13462 fix: Allocate HTTP header space for async httpd_req_t objects (IDFGH-12445)
  components/esp_http_server/src/httpd_txrx.c
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#13501 Add Padding for Odd-Length Packets in UDP Checksum (IDFGH-12490)
  examples/network/sta2eth/main/ethernet_iface.c
Labels: Status: Done, Resolution: NA

#13546 feat(esptool): merge_bin CMake target (IDFGH-12541)
  components/esptool_py/project_include.cmake
Labels: Status: Done, Resolution: Done

#13669 docs: clarify ESP_RETURN_ON_ERROR result (IDFGH-12678)
  docs/en/api-guides/error-handling.rst
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#13560 esp_eth: DP83848: correct link detection to use BMSR (IDFGH-12557)
  components/esp_eth/src/esp_eth_phy_dp83848.c
Labels: Status: Done, Resolution: NA, PR-Sync-Merge
