Repository espressif/esp-idf, pull requests merged in 2025-02, with the labels that each got.

#15081 fix(storage/fatfs): Compiler unused warnings (IDFGH-14289)
  components/fatfs/diskio/diskio_rawflash.c
  components/fatfs/vfs/vfs_fat_sdmmc.c
Labels: Status: Done, Resolution: NA

#15291 fix(esp_http_client): Fix invalid content length header (IDFGH-14528)
  components/esp_http_client/esp_http_client.c
Labels: Status: Done, Resolution: NA, PR-Sync-Merge

#15388 fix(esp_http_client): Fix host header for IPv6 address literal (IDFGH-14640)
  components/esp_http_client/esp_http_client.c
Labels: Status: Done, Resolution: NA, PR-Sync-Merge, PR-Sync-Update
